# 1.2.1 Пример

In [2]:
# Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [3]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2 Пример

In [4]:
# Пример. Выполнить следующее:
# 1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
# 2. Создать вектор размера 10, заполненный единицами.
# 3. Создать вектор размера 10, заполненный заданным числом.
# 4. Создать вектор со значениями от 10 до 19.

In [5]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


# 1.2.3 Пример

In [6]:
# Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

In [7]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, "\n", Zmax, "\n", Zmean)

0.012720278396448181 
 0.9910837717310993 
 0.48248371971925097


# 1.2.4 Пример

In [8]:
# Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [9]:
A = np.arange(25).reshape(5, 5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

In [10]:
# Выяснить результат следующих выражений:
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# 0.3 == 3 * 0.1

In [11]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 1.2.6 Пример

In [12]:
# Отсортировать массив

In [13]:
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

In [14]:
# Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [15]:
matrix = np.full((8,8), 0)
matrix[1:8:2, 1:8:2] = 1
matrix[0:8:2, 0:8:2] = 1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 1.3.2 Задание

In [16]:
# Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange.

In [17]:
matrix = np.array([np.arange(5) for i in range(5)])
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание

In [23]:
# Создать массив 3x3x3 со случайными значениями

In [24]:
matrix = np.random.random((3,3,3))
print(matrix)

[[[0.22191666 0.31281115 0.83150496]
  [0.92023467 0.80411008 0.30983464]
  [0.56655129 0.13960908 0.48389911]]

 [[0.50000487 0.58613503 0.05334289]
  [0.94042703 0.53582848 0.06259447]
  [0.6641108  0.85750628 0.21937002]]

 [[0.00558796 0.38656012 0.30715545]
  [0.33206122 0.96973676 0.58892885]
  [0.09100084 0.77110188 0.06432191]]]


# 1.3.4 Задание

In [25]:
# Создать матрицу с 0 внутри, и 1 на границах.

In [30]:
matrix = np.full((3,3), 1)
matrix[1, 1] = 0
print(matrix)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


# 1.3.5 Задание

In [31]:
# Создайте массив и отсортируйте его по убыванию.

In [38]:
import random
array = np.array([random.random() for i in range(10)])
array[::-1] = np.sort(array)
print(array)

[0.98751311 0.86467545 0.82544828 0.79900576 0.77192465 0.73062707
 0.68250594 0.6564112  0.62572248 0.43794716]


# 1.3.6 Задание

In [39]:
# Создайте матрицу, выведите ее форму, размер и размерность.

In [41]:
matrix = np.random.random((3,3))
print(matrix)
if (A.shape[0] == A.shape[1]):
  print("square")
else:
  print("rectangle")
print(matrix.shape)
print(matrix.size)

[[0.07282426 0.29529041 0.81188694]
 [0.45561408 0.06179101 0.28034809]
 [0.15921024 0.72485255 0.21602206]]
square
(3, 3)
9


# 2.2.1 Пример

In [42]:
# Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [43]:
import pandas as pd
lst = [1,2,3,4,5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


# 2.2.2 Пример

In [44]:
# Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [45]:
s1 = pd.Series([1,2,3,4,5], ['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# 2.2.3 Пример

In [46]:
# Cоздайте новый фрейм данных.

In [48]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38,25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

In [49]:
# Загрузите фрейм данных по ссылке: https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [50]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример

In [51]:
# Проанализировать характеристики фрейма данных

In [52]:
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1
                  Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0
(1313, 6)
              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000


# 2.2.6 Пример

In [53]:
# Выберите индивидуальные данные или срезы фрейма данных

In [54]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

In [55]:
# Требуется отобрать строки фрейма данных на основе некоторого 
# условия. Необходимо сформировать новый фрейм данных из пассажиров 
# первого класса.

In [56]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

In [57]:
# Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу

In [60]:
a = pd.Series([0,1], ['x', 'y'])
b = pd.Series([2,3], ['x', 'y'])
print(((a['x'] - b['x'])**2 + (a['y'] - b['y'])**2)**(1/2))

2.8284271247461903


# 2.3.2 Задание

In [61]:
# Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

In [62]:
url = "https://raw.githubusercontent.com/akmand/datasets/main/wine.csv"
dataframe = pd.read_csv(url)
dataframe

1     2     3     4    5     6     7     8     9     10    11    12  \
0    14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04  3.92   
1    13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05  3.40   
2    13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03  3.17   
3    14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86  3.45   
4    13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04  2.93   
..     ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   ...   
173  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64  1.74   
174  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70  1.56   
175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59  1.56   
176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60  1.62   
177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61  1.60   

       13  y  
0    1065  1  
1    1050  1  
2    1185  1  
3    1480  1  
4     735  1  
..    ... ..  
173   740  3  
174   750  3  
175   835  3  
176   840  3  
177   560  3  

[178 rows x 14 columns]

# 2.3.3 Задание

In [63]:
# Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5 - 2.2.7.

In [76]:
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())
print(dataframe.iloc[1:4])
print(dataframe[dataframe['4'] > 14].head(2))

       1     2     3     4    5     6     7     8     9    10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   

     13  y  
0  1065  1  
1  1050  1  
         1     2     3     4    5     6     7     8     9    10    11    12  \
175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.2  0.59  1.56   
176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.3  0.60  1.62   
177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.2  0.61  1.60   

      13  y  
175  835  3  
176  840  3  
177  560  3  
(178, 14)
                1           2           3           4           5           6  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean    13.000618    2.336348    2.366517   19.494944   99.741573    2.295112   
std      0.811827    1.117146    0.274344    3.339564   14.282484    0.625851   
min     11.030000    0

# 3.2.1 Пример

In [77]:
# Прошкалируйте числовой признак в диапазон между двумя значениями.

In [78]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2 Пример

In [79]:
# Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [83]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print(standardized)
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее: 0
Стандартное отклонение: 1.0


# 3.2.3 Пример

In [84]:
# Дан фрейм данных 
# dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
#  'B':[103.02,107.26,110.35,114.23,114.68],
#  'C':['big','small','big','small','small']})
# Необходимо масштабировать его числовые столбцы

In [85]:
import pandas as pd
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})
dfTest[['A','B']] = scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

# 3.3.2 Задание

In [86]:
# Загрузить фрейм данных по ссылке:
# https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
# Необходимо выполнить нормализацию первого числового признака 
# (sepal_length_cm) с использованием минимаксного преобразования, а 
# второго (sepal_width_cm) с задействованием z-масштабирования.

In [87]:
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
dataframe = pd.read_csv(url)
print(dataframe)

scaler_minmax = preprocessing.MinMaxScaler(feature_range = (0,1))
scaler_z = preprocessing.StandardScaler()
dataframe[['sepal_length_cm']] = scaler_minmax.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = scaler_z.fit_transform(dataframe[['sepal_width_cm']])

print(dataframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 